name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y tree

      - name: Validate folder and file structure
        run: |
          #!/bin/bash

          # Clona el repositorio y cambia a la rama del pull request
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD

          # Define tus reglas de validación aquí
          # Ejemplo: Verificar que todas las carpetas en "src" tengan el formato "nombre-numero"
          for folder in src/*; do
            if [[ ! -d $folder ]]; then
              continue
            fi

            if [[ ! $folder =~ ^src/[a-zA-Z]+-[0-9]+$ ]]; then
              echo "Error: La carpeta $folder no cumple con el formato requerido (nombre-numero)."
              exit 1
            fi

            # Ejemplo: Verificar que las carpetas contienen un archivo "README.md" y otro archivo ".txt"
            if [[ ! -f $folder/README.md ]]; then
              echo "Error: No se encontró el archivo README.md en la carpeta $folder."
              exit 1
            fi

            txt_files_count=$(find $folder -maxdepth 1 -name "*.txt" | wc -l)
            if [[ $txt_files_count -ne 1 ]]; then
              echo "Error: La carpeta $folder debe contener exactamente un archivo .txt."
              exit 1
            fi
          done
